[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/api/tickers"
  to = "/.netlify/functions/fetchSerenity?request_type=tickers"
  status = 200
  force = true

[[redirects]]
  from = "/api/orderbook/:ticker_id"
  to = "/.netlify/functions/fetchSerenity?ticker_id=:ticker_id&request_type=orderbook"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
