[build]
  publish = "public"
  functions = "functions"

# Tickers endpoint
[[redirects]]
  from = "/api/tickers"
  to = "/.netlify/functions/getTickers"
  status = 200
  force = true

# Orderbook endpoint - EXACT match for /api/orderbook/:ticker_id
[[redirects]]
  from = "/api/orderbook/:ticker_id"
  to = "/.netlify/functions/getOrderbook?ticker_id=:ticker_id"
  status = 200
  force = true

# Catch-all for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# CORS headers for API endpoints
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
    Cache-Control = "no-cache"

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
