[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/api/tickers"
  to = "/.netlify/functions/fetchSerenity"
  status = 200
  force = true

[[redirects]]
  from = "/api/orderbook/*"
  to = "/.netlify/functions/fetchOrderbook?ticker_id=:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
